# Generated by Django 4.2 on 2023-04-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="authormodel",
            fields=[
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pubmodel",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="bookmodel",
            fields=[
                (
                    "title",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("aname", models.ManyToManyField(to="lab8q3.authormodel")),
                (
                    "pname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab8q3.pubmodel",
                    ),
                ),
            ],
        ),
    ]
