# Generated by Django 4.2 on 2023-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab8q3", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookmodel", name="aname",),
        migrations.AlterField(
            model_name="bookmodel", name="date", field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="aname",
            field=models.CharField(default="", max_length=100),
        ),
    ]
