# Generated by Django 4.2 on 2023-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="marksmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.IntegerField()),
                ("physics", models.IntegerField()),
                ("chem", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="studentmodel", name="id",),
        migrations.AlterField(
            model_name="studentmodel",
            name="student_number",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
