# Generated by Django 4.2 on 2023-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_marksmodel_remove_studentmodel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksmodel",
            name="total",
            field=models.IntegerField(default="some_value"),
        ),
    ]
