# Generated by Django 4.2 on 2023-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_marksmodel_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksmodel",
            name="total",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
