# Generated by Django 4.2 on 2023-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_marksmodel_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="dummy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.IntegerField()),
            ],
        ),
    ]
