# Generated by Django 4.2 on 2023-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_delete_dummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksmodel", name="total", field=models.IntegerField(default=1),
        ),
    ]
