# Generated by Django 4.2 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_marksmodel_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksmodel",
            name="total",
            field=models.CharField(default="some_value", max_length=100),
        ),
    ]
