# Generated by Django 4.2 on 2023-05-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_marksmodel_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksmodel",
            name="student_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
