# Generated by Django 4.2 on 2023-05-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_marksmodel_student_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="marksmodel", name="id",),
        migrations.AlterField(
            model_name="marksmodel",
            name="student_number",
            field=models.PositiveIntegerField(
                default=1, primary_key=True, serialize=False
            ),
        ),
    ]
