# Generated by Django 4.2 on 2023-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="categorymodel",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("numberofvisits", models.IntegerField()),
                ("numberoflikes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="pagemodel",
            fields=[
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("URL", models.URLField(primary_key=True, serialize=False)),
                ("views", models.IntegerField()),
            ],
        ),
    ]
