# Generated by Django 4.2 on 2023-05-02 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=200)),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={"ordering": ("-timestamp",),},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=100)),
                ("options", models.ManyToManyField(to="app.option")),
            ],
        ),
    ]
