# Generated by Django 4.2 on 2023-05-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="humanmodel",
            name="phone",
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
